# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns the convex minorant of a polygon.
#'
#' @param str input character vector
#' @return characters in each element of the vector
rcpp_convex_minorant <- function(x, y) {
    .Call('rqIcm_rcpp_convex_minorant', PACKAGE = 'rqIcm', x, y)
}

#' I can do my own documentation
rcpp_hello_world <- function() {
    .Call('rqIcm_rcpp_hello_world', PACKAGE = 'rqIcm')
}

